language: python
notifications:
  email: false
python:
  - "3.6"
before_script:
  - sudo apt-get install libcr-dev mpich mpich-doc
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pip install xtal
  - pip install mpi4py
  - pip install platypus-opt
  - pip install pytest-cov
  - pip install coveralls
script:
  - cd tests
  - pytest -v --cov=ezff
after_success:
  - coveralls
